server:
  port: 8080
  servlet:
    context-path: /

rest:
  cors:
    allowed-origins: "*"

#spring:
#  jooq:
#    sql-dialect: POSTGRES
#  datasource:
#    url: jdbc:postgresql://localhost/php-crud-data
#    username: php-crud-data
#    password: php-crud-data

spring:
  jooq:
    sql-dialect: MYSQL
  datasource:
    url: jdbc:mysql://localhost/checkinlove_next_gen?useSSL=false
    username: root
    password: 1234
#spring:
#  jooq:
#    sql-dialect: H2
#  datasource:
#    url: jdbc:h2:mem:test
